--
-- TODO ?? decouple TxChatMessage from rendering and parsing (create a seam)
--  * add gptoss raw renderer/parser
--    you already have non-thinking renderer
--    and parser is pretty much one message at a time (not that complex)
--    well tested if you go this route
--  * keep a generic messages renderer/parser
